export const REDUX_ACTION_ADD = "REDUX_ACTION_ADD";
export const REDUX_ACTION_REM = "REDUX_ACTION_REM";
export const REDUX_ACTION_CLR = "REDUX_ACTION_CLR";


export const BOX1_ACTION_ADD = 'BOX1_ACTION_ADD';